version: '3'
services:
  db:
    image: mysql:8
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: number
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - my_app
    ports:
      - 3307:3306
  app:
    build:
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    depends_on:
      - db
    networks:
      - my_app

networks:
  my_app: